In [1]:
from eval import *

# IMQ-MMS

In [2]:
mode = 'IMQ-MMS'
results_npp, results_pp, results_ppw, results_cpp_sd = load_bootstrapping_results(mode)
parameters_npp, parameters_pp, parameters_ppw, parameters_cpp_sd, combination, titles = construct_parameter_configurations(mode)

In [3]:
winner_npp_1, pvals_npp_1, bsm_npp_1 = model_selection(results_npp, combination, parameters_npp, titles, mms_pc='NPP')

12it [00:41,  3.48s/it]


In [4]:
winner_pp_1, pvals_pp_1, bsm_pp_1 = model_selection(results_pp, combination, parameters_pp, titles)

12it [00:40,  3.35s/it]


In [5]:
winner_ppw_1, pvals_ppw_1, bsm_ppw_1 = model_selection(results_ppw, combination, parameters_ppw, titles)

12it [01:51,  9.29s/it]


In [6]:
winner_cpp_sd_1, pvals_cpp_sd_1, bsm_cpp_sd_1 = model_selection(results_cpp_sd, combination, parameters_cpp_sd, titles)

12it [00:44,  3.67s/it]


In [7]:
pvals_all_1 = eval_all(combination, winner_npp_1, winner_pp_1, winner_ppw_1,
                       winner_cpp_sd_1, pvals_npp_1, pvals_pp_1, pvals_ppw_1, pvals_cpp_sd_1, titles)

CPP-SD: SS and MMS-LA: rho 0.3981 p 0.0001 mean 0.3677 CI 0.3569-0.3785 achieved by max-euclidean-25-mmm-cosine
PP:     SS and MMS-RA: rho 0.4227 p 0.0001 mean 0.3947 CI 0.3861-0.4034 achieved by euclidean-pearson-25-max-min
CPP-SD: SS and MMS-LH: rho 0.4361 p 0.0001 mean 0.4127 CI 0.4055-0.4199 achieved by euclidean-pearson-50-max-pearson
CPP-SD: SS and MMS-RH: rho 0.5302 p 0.0001 mean 0.5168 CI 0.5051-0.5284 achieved by max-euclidean-25-min-pearson
PPw:    SO and MMS-LA: rho 0.4883 p 0.0001 mean 0.4607 CI 0.4478-0.4736 achieved by min-wrd-50-max
PP:     SO and MMS-RA: rho 0.4022 p 0.0001 mean 0.3821 CI 0.3751-0.3891 achieved by euclidean-pearson-25-max
CPP-SD: SO and MMS-LH: rho 0.5048 p 0.0001 mean 0.4678 CI 0.4601-0.4755 achieved by min-euclidean-50-mmm-cosine
CPP-SD: SO and MMS-RH: rho 0.5156 p 0.0001 mean 0.4766 CI 0.4657-0.4875 achieved by max-mahalanobis-25-max-manhattan
CPP-SD: OS and MMS-LA: rho 0.2838 p 0.0001 mean 0.2890 CI 0.2801-0.2980 achieved by abs*mean-euclidean-25-mi

In [8]:
bsm_top_SS, bsm_top_SO, bsm_top_OS = [], [], []
bsm_top_SS.append(bsm_cpp_sd_1[0])
bsm_top_SS.append(bsm_pp_1[1])
bsm_top_SS.append(bsm_cpp_sd_1[2])
bsm_top_SS.append(bsm_cpp_sd_1[3])
bsm_top_SO.append(bsm_ppw_1[4])
bsm_top_SO.append(bsm_pp_1[5])
bsm_top_SO.append(bsm_cpp_sd_1[6])
bsm_top_SO.append(bsm_cpp_sd_1[7])
bsm_top_OS.append(bsm_cpp_sd_1[8])
bsm_top_OS.append(bsm_cpp_sd_1[9])
bsm_top_OS.append(bsm_cpp_sd_1[10])
bsm_top_OS.append(bsm_cpp_sd_1[11])

In [9]:
ks_test(bsm_top_SS)

KstestResult(statistic=0.32017525080887776, pvalue=1.0900049460037837e-91, statistic_location=0.3393441302740732, statistic_sign=1)
KstestResult(statistic=0.34872373009107605, pvalue=3.4413976934304813e-109, statistic_location=0.30095676926376436, statistic_sign=1)
KstestResult(statistic=0.2879184130239538, pvalue=6.920910279549706e-74, statistic_location=0.44566835559966744, statistic_sign=1)
KstestResult(statistic=0.3589383107955064, pvalue=7.367749933898348e-116, statistic_location=0.2638745050448916, statistic_sign=1)
KstestResult(statistic=0.35574828635923306, pvalue=9.409566260322012e-114, statistic_location=0.2721631525947755, statistic_sign=1)
KstestResult(statistic=0.33518491202852496, pvalue=1.1059130601484301e-100, statistic_location=0.3552933670725713, statistic_sign=1)


In [10]:
ks_test(bsm_top_SO)

KstestResult(statistic=0.31200705604641527, pvalue=5.506715801513654e-87, statistic_location=-0.3212590159365808, statistic_sign=-1)
KstestResult(statistic=0.3328018413155317, pvalue=3.178288063927411e-99, statistic_location=0.33768088289696124, statistic_sign=1)
KstestResult(statistic=0.26863289630733544, pvalue=3.232656044868573e-64, statistic_location=0.4436912913179701, statistic_sign=1)
KstestResult(statistic=0.3663085071950839, pvalue=8.305814341712308e-121, statistic_location=0.2370512718726874, statistic_sign=1)
KstestResult(statistic=0.361412928122286, pvalue=1.654854925983289e-117, statistic_location=0.29652934996403313, statistic_sign=1)
KstestResult(statistic=0.31036079608970896, pvalue=4.7064746500633106e-86, statistic_location=-0.3870467584203281, statistic_sign=-1)


In [11]:
ks_test(bsm_top_OS)

KstestResult(statistic=0.38205304435619136, pvalue=9.187193792971642e-132, statistic_location=0.20431661272609675, statistic_sign=1)
KstestResult(statistic=0.36419051667900626, pvalue=2.254274853184642e-119, statistic_location=0.2632199780195771, statistic_sign=1)
KstestResult(statistic=0.40495918596299074, pvalue=1.1637936636965682e-148, statistic_location=0.13334774215542516, statistic_sign=1)
KstestResult(statistic=0.3753200675295269, pvalue=5.16757640137947e-127, statistic_location=-0.1934071259985563, statistic_sign=-1)
KstestResult(statistic=0.34689276135450564, pvalue=5.120343438794434e-108, statistic_location=-0.3057624472081441, statistic_sign=-1)
KstestResult(statistic=0.40207089024169174, pvalue=1.819724324034304e-146, statistic_location=0.18638636978222278, statistic_sign=1)


In [12]:
# Since p-values from Kolmogorov-Smirnov tests all less than .05, we next adopt Wilcoxon signed-rank tests rather than paired T-tests.
tvals_SS_1, zvals_SS_1, pvals_SS_1 = wcx_test(bsm_top_SS)
tvals_SO_1, zvals_SO_1, pvals_SO_1 = wcx_test(bsm_top_SO)
tvals_OS_1, zvals_OS_1, pvals_OS_1 = wcx_test(bsm_top_OS)

In [13]:
"""
CPP-SD: SS and MMS-LA: rho 0.3981 p 0.0001 mean 0.3677 CI 0.3569-0.3785
PP:     SS and MMS-RA: rho 0.4228 p 0.0001 mean 0.3947 CI 0.3861-0.4034
CPP-SD: SS and MMS-LH: rho 0.4347 p 0.0001 mean 0.4127 CI 0.4055-0.4199
CPP-SD: SS and MMS-RH: rho 0.5302 p 0.0001 mean 0.5168 CI 0.5051-0.5284
"""

for i in range(6):
    print('mean=%.4f [%.4f, %.4f], z=%.2f, p=%.4f' % (tvals_SS_1[i][0], tvals_SS_1[i][1], tvals_SS_1[i][2], zvals_SS_1[i], pvals_SS_1[i]))

mean=-0.0270 [-0.0409, -0.0132], z=-3.90, p=0.0001
mean=-0.0450 [-0.0571, -0.0329], z=-6.71, p=0.0000
mean=-0.1491 [-0.1695, -0.1286], z=-13.03, p=0.0000
mean=-0.0179 [-0.0280, -0.0079], z=-3.87, p=0.0001
mean=-0.1220 [-0.1358, -0.1083], z=-15.45, p=0.0000
mean=-0.1041 [-0.1189, -0.0893], z=-12.93, p=0.0000


In [14]:
"""
PPw:    SO and MMS-LA: rho 0.4883 p 0.0001 mean 0.4607 CI 0.4478-0.4736 
PP:     SO and MMS-RA: rho 0.4030 p 0.0001 mean 0.3821 CI 0.3751-0.3891 
CPP-SD: SO and MMS-LH: rho 0.5048 p 0.0001 mean 0.4678 CI 0.4601-0.4755 
CPP-SD: SO and MMS-RH: rho 0.5156 p 0.0001 mean 0.4766 CI 0.4657-0.4875
"""

for i in range(6):
    print('mean=%.4f [%.4f, %.4f], z=%.2f, p=%.4f' % (tvals_SO_1[i][0], tvals_SO_1[i][1], tvals_SO_1[i][2], zvals_SO_1[i], pvals_SO_1[i]))

mean=0.0786 [0.0634, 0.0938], z=-10.21, p=0.0000
mean=-0.0071 [-0.0201, 0.0059], z=-0.21, p=0.8304
mean=-0.0159 [-0.0346, 0.0028], z=-1.44, p=0.1498
mean=-0.0857 [-0.0966, -0.0749], z=-14.38, p=0.0000
mean=-0.0945 [-0.1070, -0.0820], z=-13.51, p=0.0000
mean=-0.0088 [-0.0230, 0.0055], z=-1.51, p=0.1318


In [15]:
"""
CPP-SD: OS and MMS-LA: rho 0.2954 p 0.0001 mean 0.2890 CI 0.2801-0.2980 
CPP-SD: OS and MMS-RA: rho 0.5627 p 0.0001 mean 0.5153 CI 0.5051-0.5255 
CPP-SD: OS and MMS-LH: rho 0.3762 p 0.0001 mean 0.3548 CI 0.3453-0.3643 
CPP-SD: OS and MMS-RH: rho 0.4763 p 0.0001 mean 0.4433 CI 0.4321-0.4544 
"""

for i in range(6):
    print('mean=%.4f [%.4f, %.4f], z=%.2f, p=%.4f' % (tvals_OS_1[i][0], tvals_OS_1[i][1], tvals_OS_1[i][2], zvals_OS_1[i], pvals_OS_1[i]))

mean=-0.2262 [-0.2411, -0.2114], z=-22.29, p=0.0000
mean=-0.0658 [-0.0771, -0.0544], z=-10.75, p=0.0000
mean=-0.1542 [-0.1646, -0.1438], z=-21.94, p=0.0000
mean=0.1605 [0.1474, 0.1735], z=-19.75, p=0.0000
mean=0.0720 [0.0583, 0.0857], z=-9.34, p=0.0000
mean=-0.0884 [-0.0971, -0.0797], z=-17.46, p=0.0000


# IMQ-rsFC

In [16]:
mode = 'IMQ-rsFC'
results = load_bootstrapping_results(mode)
parameters, combination, titles = construct_parameter_configurations(mode)

In [17]:
pvals_2, bsm_top_SS, bsm_top_SO, bsm_top_OS = [], [], [], []


for i, r in enumerate(results):

    idx, m = sorted([m for m in enumerate(mean(r, 50))],
                    key=lambda x: x[-1],
                    reverse=True)[0]
    
    if i in [0, 1, 2, 3]:
        bsm_top_SS.append((m, r[idx][-1]))
        
    if i in [4, 5, 6, 7]:
        bsm_top_SO.append((m, r[idx][-1]))
        
    if i in [8, 9, 10, 11]:
        bsm_top_OS.append((m, r[idx][-1]))
    
    if parameters[idx][0] in DSF_X_mvs:
        x = combination[i][0][0]
        
    if parameters[idx][0] in DSF_X_uvs:
        x = combination[i][0][1]

    rho, pv = run(x, combination[i][1], parameters[idx]
                  [0], parameters[idx][1], iter=10000)

    l, h = st.norm.interval(alpha=0.95,
                            loc=np.mean(r[idx][1]),
                            scale=st.sem(r[idx][1]))

    pvals_2.append(pv)

    print(titles[i] + ': ' + 'rho ' + '%.4f' % float(rho) +
          ' p ' + '%.4f' % float(pv) + ' mean ' + '%.4f' % float(m) +
                  ' CI ' + '%.4f' % float(l) + '-' + '%.4f' % float(h) + ' achieved by '+parameters[idx][0] +
          '-'+parameters[idx][1])

SS and rsFC-LA: rho 0.2272 p 0.0002 mean 0.2094 CI 0.1995-0.2194 achieved by max-euclidean
SS and rsFC-RA: rho 0.2025 p 0.0002 mean 0.1747 CI 0.1668-0.1826 achieved by mahalanobis-pearson
SS and rsFC-LH: rho 0.1465 p 0.0071 mean 0.1256 CI 0.1162-0.1350 achieved by max-mahalanobis
SS and rsFC-RH: rho 0.3600 p 0.0001 mean 0.3434 CI 0.3348-0.3520 achieved by max-mahalanobis
SO and rsFC-LA: rho 0.1345 p 0.0140 mean 0.1239 CI 0.1169-0.1310 achieved by euclidean-pearson
SO and rsFC-RA: rho 0.1412 p 0.0097 mean 0.1359 CI 0.1266-0.1452 achieved by max-pearson
SO and rsFC-LH: rho 0.2383 p 0.0001 mean 0.2254 CI 0.2147-0.2360 achieved by pearson-cosine
SO and rsFC-RH: rho 0.2580 p 0.0001 mean 0.2427 CI 0.2347-0.2508 achieved by pearson-pearson
OS and rsFC-LA: rho 0.3297 p 0.0001 mean 0.3164 CI 0.3078-0.3250 achieved by euclidean-cosine
OS and rsFC-RA: rho 0.3161 p 0.0001 mean 0.2890 CI 0.2788-0.2993 achieved by min-mahalanobis
OS and rsFC-LH: rho 0.3128 p 0.0001 mean 0.2861 CI 0.2742-0.2980 achie

In [18]:
ks_test(bsm_top_SS)

KstestResult(statistic=0.31992721480041075, pvalue=1.5213347823314866e-91, statistic_location=-0.3320461258272615, statistic_sign=-1)
KstestResult(statistic=0.3794368955245453, pvalue=6.61359141578811e-130, statistic_location=-0.24962961885446977, statistic_sign=-1)
KstestResult(statistic=0.389774547597882, pvalue=2.4848404310464714e-137, statistic_location=0.21527990579453143, statistic_sign=1)
KstestResult(statistic=0.3352181641981802, pvalue=1.0550868298298218e-100, statistic_location=-0.26834167720512386, statistic_sign=-1)
KstestResult(statistic=0.38965332569329947, pvalue=3.0458598661989156e-137, statistic_location=0.2053397989933766, statistic_sign=1)
KstestResult(statistic=0.45791574227403675, pvalue=2.9495550174583684e-192, statistic_location=0.02528017799365556, statistic_sign=1)


In [19]:
ks_test(bsm_top_SO)

KstestResult(statistic=0.3505949784365307, pvalue=2.1438549702780275e-110, statistic_location=-0.27516437320437226, statistic_sign=-1)
KstestResult(statistic=0.3642658609592575, pvalue=2.0052583832999195e-119, statistic_location=0.2786261765863451, statistic_sign=1)
KstestResult(statistic=0.40269522957451154, pvalue=6.127528444405158e-147, statistic_location=0.2001152342351314, statistic_sign=1)
KstestResult(statistic=0.32648179768441465, pvalue=2.061503533828175e-95, statistic_location=0.2806699026681077, statistic_sign=1)
KstestResult(statistic=0.3556274491958561, pvalue=1.1296261522591022e-113, statistic_location=0.23107710884499877, statistic_sign=1)
KstestResult(statistic=0.37215847046388595, pvalue=8.133841186017977e-125, statistic_location=0.24776408979328193, statistic_sign=1)


In [20]:
ks_test(bsm_top_OS)

KstestResult(statistic=0.3124087413950852, pvalue=3.2562167420678575e-87, statistic_location=-0.430519915518982, statistic_sign=-1)
KstestResult(statistic=0.3180873992880921, pvalue=1.7881157963556512e-90, statistic_location=-0.3078784837231886, statistic_sign=-1)
KstestResult(statistic=0.3695047619427754, pvalue=5.469309547242688e-123, statistic_location=-0.24170400776127327, statistic_sign=-1)
KstestResult(statistic=0.2863416353453036, pvalue=4.5481207771305154e-73, statistic_location=-0.4060807482390183, statistic_sign=-1)
KstestResult(statistic=0.31947863161715284, pvalue=2.77830933539362e-91, statistic_location=-0.37057076098220365, statistic_sign=-1)
KstestResult(statistic=0.40744509595039435, pvalue=1.45405919237102e-150, statistic_location=-0.16506834032181394, statistic_sign=-1)


In [21]:
# Since p-values from Kolmogorov-Smirnov tests all less than .05, we next adopt Wilcoxon signed-rank tests rather than paired T-tests.
tvals_SS_2, zvals_SS_2, pvals_SS_2 = wcx_test(bsm_top_SS)
tvals_SO_2, zvals_SO_2, pvals_SO_2 = wcx_test(bsm_top_SO)
tvals_OS_2, zvals_OS_2, pvals_OS_2 = wcx_test(bsm_top_OS)

In [22]:
"""
SS and rsFC-LA: rho 0.2272 p 0.0002 mean 0.2094 CI 0.1995-0.2194 
SS and rsFC-RA: rho 0.2025 p 0.0005 mean 0.1747 CI 0.1668-0.1826 
SS and rsFC-LH: rho 0.1465 p 0.0082 mean 0.1256 CI 0.1162-0.1350 
SS and rsFC-RH: rho 0.3600 p 0.0001 mean 0.3434 CI 0.3348-0.3520 
"""

for i in range(6):
    print('mean=%.4f [%.4f, %.4f], z=%.2f, p=%.4f' % (tvals_SS_2[i][0], tvals_SS_2[i][1], tvals_SS_2[i][2], zvals_SS_2[i], pvals_SS_2[i]))

mean=0.0347 [0.0209, 0.0485], z=-4.82, p=0.0000
mean=0.0838 [0.0731, 0.0944], z=-14.15, p=0.0000
mean=-0.1340 [-0.1451, -0.1228], z=-19.35, p=0.0000
mean=0.0491 [0.0360, 0.0622], z=-7.48, p=0.0000
mean=-0.1687 [-0.1813, -0.1560], z=-20.61, p=0.0000
mean=-0.2177 [-0.2258, -0.2097], z=-26.75, p=0.0000


In [23]:
"""
SO and rsFC-LA: rho 0.1304 p 0.0147 mean 0.1239 CI 0.1169-0.1310 
SO and rsFC-RA: rho 0.1412 p 0.0099 mean 0.1359 CI 0.1266-0.1452 
SO and rsFC-LH: rho 0.2383 p 0.0001 mean 0.2254 CI 0.2147-0.2360 
SO and rsFC-RH: rho 0.2580 p 0.0001 mean 0.2427 CI 0.2347-0.2508 
"""

for i in range(6):
    print('mean=%.4f [%.4f, %.4f], z=%.2f, p=%.4f' % (tvals_SO_2[i][0], tvals_SO_2[i][1], tvals_SO_2[i][2], zvals_SO_2[i], pvals_SO_2[i]))

mean=-0.0120 [-0.0220, -0.0020], z=-2.90, p=0.0038
mean=-0.1014 [-0.1139, -0.0890], z=-14.25, p=0.0000
mean=-0.1188 [-0.1284, -0.1092], z=-19.78, p=0.0000
mean=-0.0894 [-0.1048, -0.0741], z=-10.67, p=0.0000
mean=-0.1068 [-0.1197, -0.0939], z=-14.65, p=0.0000
mean=-0.0174 [-0.0265, -0.0083], z=-3.86, p=0.0001


In [24]:
"""
OS and rsFC-LA: rho 0.3344 p 0.0001 mean 0.3164 CI 0.3078-0.3250 
OS and rsFC-RA: rho 0.3161 p 0.0001 mean 0.2890 CI 0.2788-0.2993
OS and rsFC-LH: rho 0.3128 p 0.0001 mean 0.2861 CI 0.2742-0.2980
OS and rsFC-RH: rho 0.1912 p 0.0009 mean 0.1682 CI 0.1538-0.1825
"""

for i in range(6):
    print('mean=%.4f [%.4f, %.4f], z=%.2f, p=%.4f' % (tvals_OS_2[i][0], tvals_OS_2[i][1], tvals_OS_2[i][2], zvals_OS_2[i], pvals_OS_2[i]))

mean=0.0274 [0.0130, 0.0418], z=-3.82, p=0.0001
mean=0.0303 [0.0160, 0.0446], z=-3.85, p=0.0001
mean=0.1483 [0.1334, 0.1631], z=-16.80, p=0.0000
mean=0.0029 [-0.0136, 0.0195], z=-0.03, p=0.9751
mean=0.1209 [0.1028, 0.1389], z=-11.96, p=0.0000
mean=0.1179 [0.1066, 0.1293], z=-17.23, p=0.0000


In [25]:
# In testing Hypothesis 2, We corrected multiple comparisons by controlling the expected FDR at 0.05.
multipletests(pvals_SS_1+pvals_SO_1+pvals_OS_1+pvals_SS_2+pvals_SO_2+pvals_OS_2, alpha=0.05, method='fdr_bh', is_sorted=False, returnsorted=False)

(array([ True,  True,  True,  True,  True,  True,  True, False, False,
         True,  True, False,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True, False,  True,  True]),
 array([1.30399844e-004, 2.89135116e-011, 1.72019191e-038, 1.40834789e-004,
        2.41651088e-053, 5.86422267e-038, 3.04137996e-024, 8.54102157e-001,
        1.58656897e-001, 1.94785504e-046, 3.27623066e-041, 1.43802082e-001,
        7.94874691e-109, 1.06446075e-026, 1.20198622e-105, 4.72236175e-086,
        1.49865126e-020, 1.32232742e-067, 2.00566883e-006, 4.37948584e-045,
        1.01330538e-082, 1.12599530e-013, 2.06341375e-093, 4.45970060e-156,
        4.23947656e-003, 1.16665831e-045, 3.28777521e-086, 2.31164738e-026,
        3.75812807e-048, 1.40834789e-004, 1.51965599e-004, 1.42051398e-004,
        9.53447740e-063, 9.75112601e-001, 1.07955297e-032, 6.26199738e-066]),
 0.0014237991678133222,
 0.0

# rsFC-MMS

In [26]:
mode = 'rsFC-MMS'
results_npp, results_pp, results_ppw, results_cpp_sd = load_bootstrapping_results(mode)
parameters_npp, parameters_pp, parameters_ppw, parameters_cpp_sd, combination, titles = construct_parameter_configurations(mode)

In [27]:
winner_npp_3, pvals_npp_3, bsm_npp_3 = model_selection(results_npp, combination, parameters_npp, titles, mms_pc='NPP')

16it [00:21,  1.32s/it]


In [28]:
winner_pp_3, pvals_pp_3, bsm_pp_3 = model_selection(results_pp, combination, parameters_pp, titles)

16it [00:22,  1.44s/it]


In [29]:
winner_ppw_3, pvals_ppw_3, bsm_ppw_3 = model_selection(results_ppw, combination, parameters_ppw, titles)

16it [01:51,  6.95s/it]


In [30]:
winner_cpp_sd_3, pvals_cpp_sd_3, bsm_cpp_sd_3 = model_selection(results_cpp_sd, combination, parameters_cpp_sd, titles)

16it [00:24,  1.56s/it]


In [31]:
pvals_all_3 = eval_all(combination, winner_npp_3, winner_pp_3, winner_ppw_3,
                       winner_cpp_sd_3, pvals_npp_3, pvals_pp_3, pvals_ppw_3, pvals_cpp_sd_3, titles)

CPP-SD: rsFC-LA and MMS-LA: rho 0.2097 p 0.0003 mean 0.1868 CI 0.1769-0.1966 achieved by mahalanobis-mahalanobis-25-mean-min-cosine
CPP-SD: rsFC-LA and MMS-RA: rho 0.4942 p 0.0001 mean 0.4683 CI 0.4603-0.4764 achieved by cosine-pearson-50-max-min-manhattan
CPP-SD: rsFC-LA and MMS-LH: rho 0.2171 p 0.0001 mean 0.2003 CI 0.1936-0.2071 achieved by pearson-cosine-25-None-pearson
CPP-SD: rsFC-LA and MMS-RH: rho 0.3609 p 0.0001 mean 0.3492 CI 0.3424-0.3561 achieved by pearson-manhattan-50-mmm-pearson
CPP-SD: rsFC-RA and MMS-LA: rho 0.1627 p 0.0029 mean 0.1632 CI 0.1558-0.1706 achieved by pearson-cosine-50-max-manhattan
CPP-SD: rsFC-RA and MMS-RA: rho 0.3848 p 0.0001 mean 0.3676 CI 0.3589-0.3763 achieved by cosine-pearson-50-max-min-manhattan
CPP-SD: rsFC-RA and MMS-LH: rho 0.2963 p 0.0001 mean 0.2778 CI 0.2691-0.2865 achieved by pearson-mahalanobis-50-max-mahalanobis
CPP-SD: rsFC-RA and MMS-RH: rho 0.2698 p 0.0001 mean 0.2659 CI 0.2585-0.2732 achieved by euclidean-euclidean-50-max-mean-pearso

In [32]:
# In testing Hypothesis 1, We corrected multiple comparisons by controlling the expected FDR at 0.05.
multipletests(pvals_all_1+pvals_2+pvals_all_3, alpha=0.05, method='fdr_bh', is_sorted=False, returnsorted=False)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True]),
 array([0.00013332, 0.00013332, 0.00013332, 0.00013332, 0.00013332,
        0.00013332, 0.00013332, 0.00013332, 0.00013332, 0.00013332,
        0.00013332, 0.00013332, 0.0002424 , 0.0002424 , 0.00747294,
        0.00013332, 0.0139986 , 0.00994772, 0.00013332, 0.00013332,
        0.00013332, 0.00013332, 0.00013332, 0.00057137, 0.00035291,
        0.00013332, 0.00013332, 0.00013332, 0.00313482, 0.00013332,
        0.00013332, 0.00013332, 0.00013332, 0.00013332, 0.0002424 ,
        0.00013332, 0.0013332 , 0.00013332, 0.00013332, 0.00013332]),
 0.0012815105228752843,
 0.00125)